Update logger
DuckySoLucky/hypixel-discord-chat-bridge pull request #264
Opened 2024-08-09 03:00 UTC by Kathund

logger now supports errors. Also fully removed console.log so everything gets saved to a file if wanted

2024-09-06 01:25 UTC, DuckySoLucky requested changes
can be done a lot better, so don't merge this Baltraz

2024-09-21 15:51 UTC, Kathund commented
> can be done a lot better, so don't merge this Baltraz

so like?

2025-02-05 17:11 UTC, DuckySoLucky commented
resolve conflicts

2025-02-14 05:14 UTC, Zickles commented
this code sucks 👎

2025-02-14 08:40 UTC, Kathund commented
> this code sucks 👎

I agree

2025-02-14 08:44 UTC, merged